userName: sxw_2020
hello: world
server:
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    basedir: /data/logs/tomcat8-application/${spring.application.name}/
    max-http-post-size: 10485760
    accesslog:
      enabled: false
      pattern: common
      directory: logs
logging: 
  appender: console
  path: /data/logs/
  pattern:
    level: info
feign:
  client:
    config:
      default:
       loggerLevel: FULL
